### ISSUE TITLE
more on README?

### ISSUE THREAD

**Issue by crazyhottommy** [meuleman/epilogos#1]
Hi,

I am eager to play around with epilogos, could you please add a bit more README?

Thanks!
Tommy

**Comment by meuleman** [comment]
Tommy, we are in the process of updating the README, in particular on how to visualize results in a WashU epigenome browser instance.
Please take a look at the latest version, and know that we will be refining these over time.
Thanks!

**Comment by crazyhottommy** [comment]
Thank you!
