### ISSUE TITLE
only get the statePairs.txt, no starch or score.txt.gz file

### ISSUE THREAD

**Issue by ykai16** [meuleman/epilogos#10]
Hi,

After successfully run epilogos on the test data, I tried computeEpilogos_minimal.sh on my own data using the S3 mode, but got only the statePairs.txt for each chromosome, no observations.starch, scores.txt.gz or exemplarRegions.txt file. Also no error messages. I checked my input data format and it seems to be exactly the seem with the test data in the epilogo package. So I am now really puzzled..Could you please point out what could be wrong? Thanks.

Yan

**Comment by erynes** [comment]
Thanks Yan. How many samples / epigenomes do you have, and how large is your input data?  Could you also e-mail me an excerpt from your input data?  Also, please send the exact command (with all arguments) that you are using to run epilogos.

Eric

**Comment by ykai16** [comment]
Hi Eric,
Thanks a lot for the quick reply! After carefully looking into my input data, I found this is because the input matrix contains string with numerical vaules in some lines. After remove these strings, epilogos runs properly and output all the expected results.

Here is another issue I had with the visualization of the qcat files using the old WashU genome browser. I followed the steps in the qcat.md to create the files, but found that WashU cannot display the track (please see the screen shot below). Could you help look at the files and point what could be wrong? The files I used can be seen in this dropbox link:https://www.dropbox.com/sh/gdcpl9jfn8yp0kk/AACi33539cWIIXhXliaTi9BCa?dl=0

Thanks,
Yan


<img width="2429" alt="Screen Shot 2019-11-11 at 12 04 42 PM" src="https://user-images.githubusercontent.com/16323164/68606034-8bbb0700-047b-11ea-803a-a286a0b2b565.png">

**Comment by erynes** [comment]
Hi Yan, I'm glad to hear that it's working for you now.  Thanks for
including your input files and that browser shot in your reply.  That
browser shot shows a region on chr7; the input you shared only contains
data for chr1.  Could this be the problem?  If you specify a region on
chr1, does the data display properly for you?

Eric

**Comment by ykai16** [comment]
Hi Eric, Thanks for pointing that out! This is indeed the reason. The default region for WashU browser is chr7 and the centromere region of chr1, so I thought there is no signal... Thanks for the help!  

Yan

**Comment by erynes** [comment]
Hi Yan, I'm glad to hear there wasn't any issue. Thanks for using Epilogos. If any more questions come up, please let us know, we're here to help.

Eric
