### ISSUE TITLE
No reason to call this "bootstrapping" -- rather just call it sampling

### ISSUE THREAD

**Issue by meuleman** [meuleman/epilogos#12]
https://github.com/meuleman/epilogos/blob/d3786b2fec5e09e53deb4129e7e5ab1c019ed605/src/computeEpilogosPairwiseVisual.py#L223-L240

Several lines mention this, let's replace with sampling/sample to avoid confusion

**Comment by jacobquon** [comment]
[devel c4b1046] bootstrap -> sample
