### ISSUE TITLE
For bash scripts, consider using `set -u` with other options 

### ISSUE THREAD

**Issue by alexpreynolds** [meuleman/epilogos#14]
https://github.com/meuleman/epilogos/blob/80bf1f5b0846b495d40eda0cd0315c8c0d371b2c/scripts/computeEpilogos.sh#L3

With production bash scripts shared with others, I suggest using `set -u` with `-e -o pipefail`. 

This will cause the script to exit with a non-zero error, if a variable is left unset or is otherwise undefined.

This is useful when using positional variables like `${1}`, `${2}`, etc. which happens later on in this script. If a variable is left out by accident, the script will stop early.

I also saw this here:

https://github.com/meuleman/epilogos/blob/80bf1f5b0846b495d40eda0cd0315c8c0d371b2c/scripts/computeEpilogos_minimal.sh#L3

It may be useful to add `set -ueo pipeline` in here, as well:

https://github.com/meuleman/epilogos/blob/80bf1f5b0846b495d40eda0cd0315c8c0d371b2c/scripts/preprocess_data_ChromHMM.sh

**Comment by meuleman** [comment]
Hi Alex, this is outdated code -- please see Jacob's code in the `src` directory instead :-)

**Comment by alexpreynolds** [comment]
Ah, sorry. Will close this up.
