### ISSUE TITLE
Consider using `requirements.txt` at the root level to specify dependencies

### ISSUE THREAD

**Issue by alexpreynolds** [meuleman/epilogos#15]
Having a `requirements.txt` file at the root level of the project makes installing dependencies as simple as: `pip install -r requirements.txt`.

You can edit this file whenever new dependencies are needed, without having to keep track of the list of packages in the project README. 

Another advantage is that you can specify specific or minimum versions of numpy, etc. in this text file. This helps with making a reproducible setup on other systems, in case you need to debug things. Newer versions of numpy etc. can change function parameters and so on, which could make your code dependent on specific versions.

To create this file with a current environment where you know things are working, you can run `pip freeze > requirements.txt` in the root directory. The file will be a list of all the dependencies and versions (I think).

This could also be generally useful later on for packaging.

**Comment by jacobquon** [comment]
[devel 616185a]
