### ISSUE TITLE
Consider having one entry point to running epilogos in various forms

### ISSUE THREAD

**Issue by alexpreynolds** [meuleman/epilogos#17]
This may be looked at in the course of preparing epilogos for distribution via PyPI, but without reading the README and just looking at the `scripts` and `src` directories, I wasn't quite sure what the starting point or entry point was to running things. 

A lot of people don't read documentation and just jump in. If I didn't read the README, I'd have assumed `src/epilogos.py` might be the starting point. 

Perhaps simplifying things to a dedicated, single "Pythonic" entry point might be helpful. This could call either the Slurm and single-node compute mode of the epilogos kit, instead of pointing users to one or another script.

https://amir.rachum.com/blog/2017/07/28/python-entry-points/

https://chriswarrick.com/blog/2014/09/15/python-apps-the-right-way-entry_points-and-scripts/

**Comment by jacobquon** [comment]
Was planning on doing something like this for the final build. Thanks a bunch for the links though because I didn't really have an idea of where to start
