### ISSUE TITLE
Consider using `click` library to handle command-line options

### ISSUE THREAD

**Issue by alexpreynolds** [meuleman/epilogos#18]
https://github.com/meuleman/epilogos/blob/80bf1f5b0846b495d40eda0cd0315c8c0d371b2c/src/columnSplitterAdsera.py#L108-L127

Using `click` or similar libraries could help simplify handling options (and boolean-flag options).

**Comment by jacobquon** [comment]
Yeah, probably should have just used click here. This was just a quick script I wrote for personal use so didn't really put much thought into it. I'll remove it from the repo
[devel f290f46]
