### ISSUE TITLE
Consider using `sys.stderr.write` or logging library in place of `print`

### ISSUE THREAD

**Issue by alexpreynolds** [meuleman/epilogos#19]
https://github.com/meuleman/epilogos/blob/80bf1f5b0846b495d40eda0cd0315c8c0d371b2c/src/columnSplitterAdsera.py#L65-L67

The `print` function hides that it prints by default to standard error, and it doesn't work the same between Python 2 and 3. Using `sys.stderr.write` is explicit and portable, and isn't much more typing. 

I would suggest replacing `print()` with a `sys.stderr.write('\n')` or similar to add newline characters. Newlines could also be added to previous `print` calls.

If these print commands are used for logging, the `logging` functionality might be useful to look into (https://docs.python.org/3/library/logging.html) for more explicit control of where messages go.

**Comment by jacobquon** [comment]
@alexpreynolds Do you think it's still worth swapping if we're not planning on supporting Python 2?

**Comment by alexpreynolds** [comment]
Seems reasonable to leave this as-is.
