### ISSUE TITLE
Consider using Python `None` instead of string to represent null value

### ISSUE THREAD

**Issue by alexpreynolds** [meuleman/epilogos#21]
https://github.com/meuleman/epilogos/blob/80bf1f5b0846b495d40eda0cd0315c8c0d371b2c/src/computeEpilogosSlurm.py#L30

Instead of using a default string called `null`, I would suggest using the Python `None` keyword to define a null value.

Later on, comparisons can be made more "Pythonic", e.g.:

https://github.com/meuleman/epilogos/blob/80bf1f5b0846b495d40eda0cd0315c8c0d371b2c/src/computeEpilogosSlurm.py#L73-L74

can become:

```
if not expFreqDir: print("Background Directory = {}".format(outputDirPath))
```

https://github.com/meuleman/epilogos/blob/80bf1f5b0846b495d40eda0cd0315c8c0d371b2c/src/computeEpilogosSlurm.py#L83-L84

can become a simpler ternary, perhaps:

```
expFreqDir = outputDirectory if not expFreqDir else None
```

**Comment by alexpreynolds** [comment]
I also noticed this usage here:

https://github.com/meuleman/epilogos/blob/80bf1f5b0846b495d40eda0cd0315c8c0d371b2c/src/minimalEpilogos.py#L31

**Comment by jacobquon** [comment]
These were old files, I got rid of these parameters in the newer versions anyway but will definitely keep the NoneType in mind in the future. I think there are still some files where I'm using "null"
[devel 4aca73a]
