### ISSUE TITLE
Consider exposing Slurm-specific parameters to `click` options

### ISSUE THREAD

**Issue by alexpreynolds** [meuleman/epilogos#22]
https://github.com/meuleman/epilogos/blob/80bf1f5b0846b495d40eda0cd0315c8c0d371b2c/src/computeEpilogosSlurm.py#L378-L383

Instead of hardcoding Slurm parameters like partition, memory, tasks-per-CPU etc., consider exposing them via `click` options. These parameters could be set to Altius-specific defaults, to make the kit easier to run locally.

**Comment by jacobquon** [comment]
Totally agree here. The partition was just for me now while I've been testing slurm. Probably best to put memory and ntasks as parameters, but for would like to at least get a better handle on what their values should be first.
