### ISSUE TITLE
Consider using touch approach to create empty files

### ISSUE THREAD

**Issue by alexpreynolds** [meuleman/epilogos#23]
Opening and immediately closing a file handle looks a bit odd. Is this perhaps being used to create an empty file?

https://github.com/meuleman/epilogos/blob/80bf1f5b0846b495d40eda0cd0315c8c0d371b2c/src/computeEpilogosSlurm.py#L365-L373

It might be harmless and work fine, if so, but for readability, there are other ways to touch a file that might be a bit clearer, e.g.:

```
from pathlib import Path

Path('path/to/file').touch()
```

**Comment by jacobquon** [comment]
Ah yes, should have just done this. Forgot about touch
[devel c73c2a6]
