### ISSUE TITLE
Uncertain what the use of `sleep` here is for

### ISSUE THREAD

**Issue by alexpreynolds** [meuleman/epilogos#25]
https://github.com/meuleman/epilogos/blob/80bf1f5b0846b495d40eda0cd0315c8c0d371b2c/src/computeEpilogosSlurm.py#L463-L466

Is there a reason you use `sleep` here, and different time values? (Is it to delay submission of separate jobs to the cluster?)

**Comment by jacobquon** [comment]
Yeah, the sleep is just so that the I'm not spamming the cluster with "sacct --format=JobID%18,JobName%50,State%10 --jobs" commands when I'm checking whether or not they're finished. I'll add a comment though. 
[devel f900832]
