### ISSUE TITLE
Negative values interpretation

### ISSUE THREAD

**Issue by asalhab** [meuleman/epilogos#29]
Hello,

I wounder if you can elaborate on the interpretation of the negative values in epilogos?
Another question is: does the high value at a particular poistion means that the state at this particular position is the same across all the used tracks? .i.e not so much variability across the different tracks?

Thank you!
Abdul

**Comment by meuleman** [comment]
Hi Abdul,

Negative values (for individual states) are the result of these states being observed (at a given position) at levels lower than what is expected genome wide.  Summed across all states though, epilogos scores are always non-negative.

High values of epilogos scores indicate that the occurrence pattern of states across biosamples deviates from what can be expected genome-wide. In the simplest case (saliency metric S1) this is based on average genome-wide occurrences of individual states, but other metrics (S2, S3) take into account more complex background models (e.g. co-occurrence of states, relationships between biosamples).  Epilogos does not necessarily tell you something about variability across tracks/biosamples, at least not in the case of metric S1.

Hope this helps

**Comment by asalhab** [comment]
Hi @meuleman 
Thank you for the clarifications of my both questions! that was helpful.

Regarding Q2 I should have been more precise. Let's assume we have two TSS positions, both have high values but different patterns occurences. The first TSS patterns consist of only one state, while the second TSS patterns consist of 4 states. Then, can we conclude that TSS1 state variability across biosamples is less compared to the one of TSS2 (in case of meteric S1)?

A side track question: I wonder if epilogos was developed specifically for summarizing chromHMM states across biosamples? or in principle can it be applied on other type of tracks (states/segemnts from other type of data. eg. methylation states with n=4)? If so, are there any considerations need to be taken into account (e.g tuning parameters, interpretation .... )?

Thank you!
