### ISSUE TITLE
qcat file specification

### ISSUE THREAD

**Issue by crazyhottommy** [meuleman/epilogos#4]
Hi,

Could you please give some specification of the output?

Thanks,
Tommy

**Comment by alexpreynolds** [comment]
After extraction with gunzip or bgzip, the "qcat" output file is a BED4 (four-column BED) formatted file.

The first three columns represent the genomic interval or bin that contains histone modifications used to generate chromatin state calls, as described here: http://egg2.wustl.edu/roadmap/web_portal/chr_state_learning.html

The fourth column contains a JSON-like string in "qcat" or "quantitative category" format, which describes a 15-, 18- or 25-element array of "state: value" pairs. These pairs are the chromatin states ordered by their per-state contribution to the overall epilogos score (i.e., the overall score is the sum of all individual per-state values).

A complete description of the quantitative category format is provided at the WashU Epigenome Browser wiki: http://wiki.wubrowse.org/QuantitativeCategorySeries

**Comment by crazyhottommy** [comment]
Hi, the output now has changed to some other format rather than qcat. How should we visualize it now? I was using https://github.com/deeptools/pyGenomeTracks/issues/6

**Comment by meuleman** [comment]
Good point Ming -- we've indeed moved away from the qcat format, to make things more portable for downstream use cases.

From the README (https://github.com/Altius/epilogos/#output):
`scores.txt.gz` is a compressed file (compressed using bgzip) containing all sites and the signed contributions from each state to the metric at each site. Columns 1-3 hold the site's coordinates. Column 4 holds the contribution from state 1, column 5 holds the contribution from state 2, etcetera; if there are n states, the file will contain n + 3 columns. This file can be used for downstream analyses or visualization.

Apologies for the inconvenience. Hopefully the authors of deeptools will be able to accommodate these changes.

-Wouter.

**Comment by crazyhottommy** [comment]
No problem. It will be nice to at least have a function to convert the scores.txt.gz to qcat

**Comment by meuleman** [comment]
Actually, this exists -- please see:
https://github.com/Altius/epilogos/blob/master/qcat.md

**Comment by asalhab** [comment]
Hello @meuleman  @alexpreynolds 
The above mentioned link poinitng to the conveting fucntion ( `scores.txt.gz to qcat `) is broken. could you please provide a working link?

**Comment by meuleman** [comment]
We have retired the qcat file format, since switching to higlass for epilogos score visualization.
However, here's a link to a legacy version of the file:
https://github.com/meuleman/epilogos/blob/b3ed29466fb6874096d087b99407cd7bd26e1550/qcat.md

**Comment by asalhab** [comment]
Thanks a lot for the quick reply!
