### ISSUE TITLE
why need to process by chromosome 

### ISSUE THREAD

**Issue by crazyhottommy** [meuleman/epilogos#7]
Hi,

I want to know the reason why one needs to process by chromosome using `computeEpilogos_singleChromosomeSingleProcessor.sh` . Is it because the memory usage is too big if I process all chromosomes at once? 

Thanks,
Tommy

**Comment by meuleman** [comment]
Not the memory usage, but it is just more efficient in terms of CPU time
(assuming the availability of a compute cluster)

-Wouter.

**Comment by crazyhottommy** [comment]
Thanks! I run the test run in the READEME. it only takes several minutes to finish. if process 24 chromosomes together, it should finish within hours (assume linear performance)?

**Comment by crazyhottommy** [comment]
I just tested by chromosome, the run is pretty fast.  one thing, the output `qcat.bed.gz` file is always the same name even if I process by chromosome, I have to put the output in a separate folder and then merge all the chromosomes. It will be nice if you can prefix all the output (including intermediate files) with `chr`:

e.g.

`chr1_qcat.bed.gz`
`chr1_Q.txt`

Thx!

**Comment by crazyhottommy** [comment]
I guess it is not an urgent problem. I also checked https://github.com/Altius/epilogos/blob/master/scripts/computeEpilogos.sh and you are putting different chromosome output with a different folder name. closing it now.
