### ISSUE TITLE
Question about groupSpec argument

### ISSUE THREAD

**Issue by joscho92** [meuleman/epilogos#8]
Hi, I'm trying to use epilogos and am confused about the groupSpec argument. With how I understand the documentation and comments in the epilogos code, it appears that groupSpec is supposed to state which columns should be included in analysis, and that the first sample (from column 4) should be "1" in this argument because it is the first sample. If this is wrong, please let me know.

Based on this understanding, if I have 9 samples, I would expect "1-9" to work for the groupSpec argument, and it does, but I also tried some other inputs to make sure I understood, such as "2-10", which also works and has slightly different outputs to the scores.txt.gz file. Following that trend, "3-11" raises an error:

> /usr/local/bin/computeEpilogos_minimal.sh: line 213: 390467 Segmentation fault      (core dumped) $EXE1 $infile1 $metric $numStates $outfileP $outfileQ $outfileNsites $groupAspec $groupBspec $outfileRand $outfileQB > ${outdir}/${jobName}.stdout 2> ${outdir}/${jobName}.stderr

But "4-12" works and so does "4-13".

This is from my input file:
chr3	0	1000	8	8	8	8	8	8	8	8	8
chr3	1000	2000	8	8	8	8	8	8	8	8	8
chr3	2000	3000	8	8	8	8	8	8	8	8	8
chr3	3000	4000	8	8	8	8	8	8	8	8	8
chr3	4000	5000	8	8	8	8	8	8	8	8	8

This is the command I run (for "4-12"):

> computeEpilogos_minimal.sh 04epilogos_input_by_chr/chr3.txt 13 1 05epilogos_output_by_chr/chr3 "4-12" > 05epilogos_output_by_chr/chr3/scores.txt.gz

Any input on this topic would be appreciated.

**Comment by erynes** [comment]
Thanks for asking. Your interpretation is exactly correct. Just now, I created a sample infile consisting of the five lines you provided, and I ran it with all the specifications you tried:  "1-9", "2-10", "3-11", "4-12", and "4-13". Only the correct one, "1-9", works for me; all the others fail when I run with those. The program checks for other errors in the input parameters and reports helpful error messages when they occur, but unfortunately it assumes the user will not include any nonexistent samples in the groupSpec and doesn't report a helpful error message when s/he does. I'll consider adding a test/message for this case. Thanks again!  --Eric
